[package]
name = "hecto"
version = "0.1.0"
authors = ["Philipp Flenker <hello@philippflenker.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.22.1"
unicode-segmentation = "1"
